# ============================================
# ~/.zshrc — Global Zsh Configuration
# ============================================
# Shared across macOS, WSL, Linux and MSYS2.
#
# Design rules (keep startup under ~150ms):
#   1. Never fork a subprocess at startup. Cache its output to a
#      file instead and re-source that. See _dot_cache_eval().
#   2. Never source a tool's init script eagerly if a stub will do.
#      See common/lazy.sh.
#   3. Oh My Zsh's core is NOT loaded. Plugins live in
#      ~/.oh-my-zsh/custom/plugins and are sourced directly, which
#      skips OMZ's loader, compaudit and 20+ lib files.
#   4. Non-interactive and AI-agent shells take a fast path that
#      skips the prompt, completions and line-editor plugins.
#
# Benchmark with:  dotfiles-doctor bench
# ============================================

# ============================================
# 0. Fast path — non-interactive shells
# ============================================
# Scripts, `zsh -c`, scp/rsync and CI never need a prompt,
# completions, syntax highlighting or autosuggestions. Bail out
# early with just env + aliases so they stay near-instant.
if [[ $- != *i* ]]; then
    DOTFILES_DIR="${DOTFILES_DIR:-$HOME/.dotfiles}"
    DOTFILES_MINIMAL=1
    [[ -f "$DOTFILES_DIR/install.sh" ]] && source "$DOTFILES_DIR/install.sh"
    return 0
fi

# ============================================
# 1. Platform detection (no forks)
# ============================================
# $OSTYPE is a zsh builtin parameter — free, unlike `uname -s`.
case "$OSTYPE" in
    darwin*)         DOTFILES_PLATFORM=macos ;;
    msys*|cygwin*)   DOTFILES_PLATFORM=msys2 ;;
    linux*)          DOTFILES_PLATFORM=linux ;;
    *)               DOTFILES_PLATFORM=unknown ;;
esac

# ============================================
# 2. Powerlevel10k instant prompt
# ============================================
# Must stay near the top. Nothing above this may write to the
# console or read input. This renders the prompt from cache before
# the rest of the file runs, so the shell *feels* instant even
# while the remaining work finishes.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ============================================
# 3. Cache helpers
# ============================================
# _dot_cache_eval lives in common/env.sh so macOS, WSL, MSYS2 and
# Git Bash all share one implementation. It is not needed until
# os/*.sh runs (section 9), by which point env.sh has defined it.
DOTFILES_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
[[ -d $DOTFILES_CACHE ]] || command mkdir -p "$DOTFILES_CACHE"

# Completions generated by tools live here and are put on FPATH so
# compinit picks them up with zero forks at startup.
DOTFILES_COMPDIR="$DOTFILES_CACHE/completions"
[[ -d $DOTFILES_COMPDIR ]] || command mkdir -p "$DOTFILES_COMPDIR"

# _dot_source <file...>
#   Source a file, byte-compiling it first if the .zwc is stale.
#   zcompile turns the file into bytecode, which cuts parse time
#   on large plugins (syntax-highlighting is ~2000 lines).
_dot_source() {
    local f
    for f in "$@"; do
        [[ -r $f ]] || continue
        if [[ ! -s ${f}.zwc || $f -nt ${f}.zwc ]]; then
            zcompile -R -- "$f" 2>/dev/null
        fi
        source "$f"
    done
}

# ============================================
# 4. AI agent / automation detection
# ============================================
# Claude Code and similar tools run commands through your login
# shell, so they pay full startup cost on EVERY command. They also
# have no use for a fancy prompt, autosuggestions or syntax
# highlighting — those are purely human-facing.
#
# Detecting them lets us skip ~150ms of line-editor setup per call,
# which compounds hard across an agent session.
DOTFILES_IS_AGENT=0
if [[ -n $CLAUDECODE || -n $AI_AGENT || -n $CURSOR_TRACE_ID \
   || -n $AIDER_MODEL || $TERM_PROGRAM == vscode-agent ]]; then
    DOTFILES_IS_AGENT=1
fi
export DOTFILES_IS_AGENT

# ============================================
# 5. History
# ============================================
HISTFILE="$HOME/.zsh_history"
HIST_STAMPS="mm/dd/yyyy"
if [[ $DOTFILES_PLATFORM == msys2 ]]; then
    # Smaller history — NTFS makes large history files slow to load.
    HISTSIZE=50000
    SAVEHIST=50000
else
    HISTSIZE=1000000
    SAVEHIST=1000000
fi
setopt APPEND_HISTORY             # Add to the history file, don't overwrite.
setopt EXTENDED_HISTORY           # Record timestamp and duration.
setopt HIST_EXPIRE_DUPS_FIRST     # Trim duplicates first when full.
setopt HIST_FIND_NO_DUPS          # Don't show a line already found.
setopt HIST_IGNORE_ALL_DUPS       # Drop the older copy of a repeat.
setopt HIST_IGNORE_DUPS           # Don't record an immediate repeat.
setopt HIST_IGNORE_SPACE          # Leading space = don't record.
setopt HIST_REDUCE_BLANKS         # Tidy whitespace before recording.
setopt HIST_SAVE_NO_DUPS          # Don't write duplicates to the file.
setopt HIST_VERIFY                # Expand !! for review, don't run it.
setopt INC_APPEND_HISTORY         # Write immediately, not at exit.
setopt SHARE_HISTORY              # Share across live sessions.
SHELL_SESSION_HISTORY=0           # macOS: disable per-session history.

# ============================================
# 6. Core shell options
# ============================================
setopt AUTO_CD                    # `foo` = `cd foo` for directories.
setopt AUTO_PUSHD                 # cd pushes onto the dir stack.
setopt PUSHD_IGNORE_DUPS          # Keep that stack clean.
setopt PUSHD_SILENT               # Don't print the stack every cd.
setopt EXTENDED_GLOB              # ^ # ~ globbing operators.
setopt GLOB_DOTS                  # Globs match dotfiles too.
setopt INTERACTIVE_COMMENTS       # Allow # comments when typing.
setopt LONG_LIST_JOBS             # Verbose job list.
setopt NO_BEEP                    # No terminal bell.
setopt NO_FLOW_CONTROL            # Free up Ctrl-S / Ctrl-Q.
setopt MULTIOS                    # Multiple redirections.
setopt NUMERIC_GLOB_SORT          # file10 sorts after file9.
setopt PROMPT_SUBST               # Expansions in the prompt.

# ============================================
# 7. Completions
# ============================================
# compinit is one of the biggest fixed costs in any zsh startup.
# Two optimisations:
#   * -C skips the security audit (compaudit), worth ~60ms.
#   * We only run the full audited compinit once every 24h.
# The dump is also byte-compiled, which roughly halves load time.
fpath=("$DOTFILES_COMPDIR" $fpath)

autoload -Uz compinit
_dot_zcompdump="$DOTFILES_CACHE/zcompdump-${ZSH_VERSION}"

if (( DOTFILES_IS_AGENT )); then
    # Agents don't tab-complete. Load the dump without scanning.
    compinit -C -d "$_dot_zcompdump"
else
    # Zsh glob qualifier: N = null-glob, mh+24 = modified 24+ hours ago.
    # If the dump is missing or a day old, do the full audited init.
    if [[ -n $_dot_zcompdump(#qN.mh+24) || ! -s $_dot_zcompdump ]]; then
        compinit -d "$_dot_zcompdump"
        # Compile in the background so this startup doesn't wait.
        { zcompile -R -- "$_dot_zcompdump" } &!
    else
        compinit -C -d "$_dot_zcompdump"
    fi
fi
unset _dot_zcompdump

# Completion behaviour
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*:descriptions' format '%F{yellow}-- %d --%f'
zstyle ':completion:*:warnings'     format '%F{red}-- no matches --%f'
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$DOTFILES_CACHE/zcompcache"
# Don't offer files we'd never want to edit.
zstyle ':completion:*:*:vim:*:*files' ignored-patterns '*.pyc|*.o|*.so'

# ============================================
# 8. Key bindings
# ============================================
# Emacs bindings by default — this matches the behaviour of the
# previous config. For vi bindings, set DOTFILES_VI_MODE=1 in
# ~/.zshrc.local (see section 12).
if [[ ${DOTFILES_VI_MODE:-0} == 1 ]]; then
    bindkey -v
    export KEYTIMEOUT=1
    bindkey '^R' history-incremental-search-backward
    bindkey -M viins '^A' beginning-of-line
    bindkey -M viins '^E' end-of-line
else
    bindkey -e
fi

# Search history for what you've already typed (arrow keys).
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^[[A' up-line-or-beginning-search
bindkey '^[[B' down-line-or-beginning-search
bindkey '^[OA' up-line-or-beginning-search
bindkey '^[OB' down-line-or-beginning-search

bindkey '^[[1;5C' forward-word          # Ctrl-Right
bindkey '^[[1;5D' backward-word         # Ctrl-Left
bindkey '^[[3~'   delete-char           # Delete
bindkey '^[[H'    beginning-of-line     # Home
bindkey '^[[F'    end-of-line           # End

# Edit the current command line in $EDITOR with Ctrl-X Ctrl-E.
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^X^E' edit-command-line

# ============================================
# 9. Dotfiles — env, aliases, functions, lazy loaders, AI helpers
# ============================================
# install.sh sources common/*.sh in a defined order, then the
# OS-specific file. Loaded BEFORE the line-editor plugins so that
# syntax highlighting knows about our aliases and functions.
DOTFILES_DIR="${DOTFILES_DIR:-$HOME/.dotfiles}"
[[ -f "$DOTFILES_DIR/install.sh" ]] && source "$DOTFILES_DIR/install.sh"

# ============================================
# 10. Plugins
# ============================================
# Sourced directly from the Oh My Zsh custom directory WITHOUT
# loading Oh My Zsh itself. OMZ's oh-my-zsh.sh sources 20+ lib
# files and runs compaudit; we want none of that.
#
# Order matters: syntax highlighting must come last so it can see
# every alias, function and widget defined above it.
ZSH="${ZSH:-$HOME/.oh-my-zsh}"
_dot_plugdir="${ZSH_CUSTOM:-$ZSH/custom}/plugins"

if (( ! DOTFILES_IS_AGENT )); then
    # --- you-should-use: nags when you type a command that has an alias
    export YSU_MESSAGE_POSITION="after"
    export YSU_HARDCORE=0            # Warn, don't refuse to run.
    export YSU_MODE=BESTMATCH        # Only show the single best alias.
    _dot_source "$_dot_plugdir/you-should-use/you-should-use.plugin.zsh"

    # --- zsh-autosuggestions: greys out a suggestion from history
    ZSH_AUTOSUGGEST_STRATEGY=(history completion)
    ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'
    # Don't try to suggest for enormous pastes — that's a known stall.
    ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
    # Use async fetching so a slow suggestion never blocks typing.
    ZSH_AUTOSUGGEST_USE_ASYNC=1
    ZSH_AUTOSUGGEST_MANUAL_REBIND=1  # Big win: skips rebinding every widget.
    _dot_source "$_dot_plugdir/zsh-autosuggestions/zsh-autosuggestions.zsh"
    bindkey '^ ' autosuggest-accept  # Ctrl-Space accepts the suggestion.

    # --- OMZ `aliases` plugin: `acs` prints a grouped alias cheatsheet
    _dot_source "$ZSH/plugins/aliases/aliases.plugin.zsh"
fi

# ============================================
# 11. Prompt
# ============================================
# Powerlevel10k, loaded directly rather than through OMZ's theme
# engine. Agents get a plain one-line prompt instead — they never
# read it, and p10k costs ~90ms plus per-command hooks.
if (( DOTFILES_IS_AGENT )); then
    PROMPT='%~ %# '
    RPROMPT=''
else
    _dot_source "${ZSH_CUSTOM:-$ZSH/custom}/themes/powerlevel10k/powerlevel10k.zsh-theme"
    [[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
fi

# ============================================
# 12. Local overrides (never committed)
# ============================================
# Machine-specific settings, secrets and experiments belong here.
# ~/.zshrc.local is deliberately not tracked by git.
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# ============================================
# 13. Syntax highlighting — MUST BE LAST
# ============================================
# This plugin wraps every ZLE widget that exists at the moment it
# loads. Anything defining widgets after it will not be highlighted.
if (( ! DOTFILES_IS_AGENT )); then
    ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
    # Cap highlighting on very long lines to avoid a visible stall.
    ZSH_HIGHLIGHT_MAXLENGTH=512
    _dot_source "$_dot_plugdir/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi

unset _dot_plugdir
